export const config = {
  DESKTOP_WIDTH: 769,
  TABLET_WIDTH: 480,
  DESKTOP_NEXT_CARDS_COUNT: 4,
  TABLET_NEXT_CARDS_COUNT: 2,
  MOBILE_NEXT_CARDS_COUNT: 1,
  DESKTOP_START_CARDS_COUNT: 16,
  TABLET_START_CARDS_COUNT: 8,
  MOBILE_START_CARDS_COUNT: 5,
  MAX_SHORT_MOVIE_DURATION:40,
};

Object.freeze(config);